sonar.projectKey=com.medibook:medibook-frontend
sonar.projectName=MediBook - Frontend (React + Vite)
sonar.projectVersion=0.0.0

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.jsx,**/*.test.js

sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.host.url=http://localhost:9000
sonar.token=sqp_45c822737654a3209f249a5ed6661fb211d62c2c